Repository BinaryStudioAcademy/bsa-2019-depot, pull requests merged in 2019-08, with the labels that each got.

#11 New/sequelize config
  .gitignore
  README.md
  server/.env.example
  server/.sequelizerc
  server/config/.gitkeep
  server/config/db.config.js
  server/data/db/connection.js
  server/package.json
Labels: enhancement

#13 New/basic routing
  client/package.json
  client/src/containers/.gitkeep
  client/src/containers/Routing/index.jsx
  client/src/scenes/Home/index.jsx
Labels: enhancement

#14 New/basic redux saga
  client/package.json
  client/src/reducers/index.js
  client/src/sagas/index.js
  client/src/scenes/Home/index.jsx
  client/src/store.js
Labels: enhancement

#25 New/backend use require
  server/.babelrc
  server/.sequelizerc
  server/config/db.config.js
  server/data/db/connection.js
  server/data/migrations/20190806094300-create-user.js
  server/data/models/example.js
  server/data/models/index.js
  server/data/models/user.js
  server/package.json
Labels: enhancement

#22 New/issues page
  client/package.json
  client/src/components/.gitkeep
  client/src/components/IssuesList/index.jsx
  client/src/components/IssuesList/styles.module.scss
  client/src/containers/IssuesTab/index.jsx
  client/src/containers/IssuesTab/reducer.js
  client/src/containers/IssuesTab/sagas.js
  client/src/containers/IssuesTab/styles.module.scss
  client/src/helpers/.gitkeep
  client/src/helpers/imageHelper.js
  client/src/reducers/index.js
  client/src/routines/routines.js
  client/src/sagas/index.js
  client/src/services/.gitkeep
  client/src/services/issuesService.js
  client/src/store.js
Labels: enhancement

#24 feat: Add saga for login
  client/package.json
  client/src/helpers/webApiHelper.js
  client/src/reducers/index.js
  client/src/sagas/auth/actions.js
  client/src/sagas/auth/reducer.js
  client/src/sagas/auth/saga/watchers.js
  client/src/sagas/auth/saga/workers/index.js
  client/src/sagas/auth/saga/workers/login.js
  client/src/sagas/auth/types.js
  client/src/sagas/index.js
  client/src/sagas/profile/actions.js
  client/src/sagas/profile/reducer.js
  client/src/sagas/profile/types.js
  client/src/scenes/Login/index.jsx
  client/src/services/authService.js
Labels: enhancement

#28 New/frontend create issue page
  client/package.json
  client/src/containers/CreateIssue/index.jsx
  client/src/containers/CreateIssue/styles.module.scss
Labels: enhancement

#31 New/commit history page
  README.md
  client/package.json
  client/src/components/CommitsList/index.jsx
  client/src/components/CommitsList/styles.module.scss
  client/src/containers/CommitsPage/index.jsx
  client/src/containers/CommitsPage/reducer.js
  client/src/containers/CommitsPage/sagas.js
  client/src/containers/CommitsPage/styles.module.scss
  client/src/reducers/index.js
  client/src/routines/routines.js
  client/src/sagas/index.js
  client/src/services/branchesService.js
  client/src/services/commitsService.js
  server/api/routes/repo.route.js
  server/api/services/branch.service.js
  server/api/services/commit.service.js
Labels: enhancement

#30 New/code page with mocks
  client/src/components/RepoFileTree/index.jsx
  client/src/components/RepoFileTree/styles.module.scss
  client/src/components/RepoReadme/index.jsx
  client/src/components/RepoReadme/styles.module.scss
  client/src/containers/Routing/index.jsx
  client/src/scenes/CodeTab/index.jsx
  client/src/scenes/CodeTab/styles.module.scss
Labels: enhancement

#33 New/use real data to sign in/up
  client/src/containers/PrivateRoute/index.jsx
  client/src/scenes/Login/index.jsx
  client/src/scenes/Signup/index.jsx
  client/src/scenes/Signup/sagas.js
  client/src/services/authService.js
  server/api/services/auth.service.js
  server/api/services/user.service.js
  server/config/passport.config.js
  server/data/migrations/20190806094300-create-user.js
  server/data/models/index.js
  server/data/models/user.js
  server/data/repositories/base.repository.js
  server/data/repositories/user.repository.js
  server/data/seed-data/users.seed.js
  server/data/seeders/20190807084512-demo-user.js
  server/helpers/crypro.helper.js
  server/package.json
  server/server.js
Labels: enhancement

#37 New/implement header for authorized users with redux
  client/src/components/Spinner/index.jsx
  client/src/containers/Header/index.jsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/PrivateRoute/index.jsx
  client/src/containers/Profile/reducer.js
  client/src/containers/Profile/sagas.js
  client/src/containers/Routing/index.jsx
  client/src/helpers/webApiHelper.js
  client/src/reducers/index.js
  client/src/routines/routines.js
  client/src/sagas/auth/actions.js
  client/src/sagas/auth/reducer.js
  client/src/sagas/auth/saga/watchers.js
  client/src/sagas/auth/saga/workers/index.js
  client/src/sagas/auth/saga/workers/login.js
  client/src/sagas/auth/types.js
  client/src/sagas/index.js
  client/src/sagas/profile/actions.js
  client/src/sagas/profile/reducer.js
  client/src/sagas/profile/types.js
  client/src/scenes/Header/index.jsx
  client/src/scenes/Login/index.jsx
  client/src/scenes/MainPage/index.jsx
  client/src/scenes/Signup/actions.js
  client/src/scenes/Signup/index.jsx
  client/src/scenes/Signup/sagas.js
  client/src/services/authService.js
  client/src/services/signupService.js
  client/src/styles/assets/icons/burger.svg
  client/src/styles/assets/icons/dropdown.svg
  client/src/styles/assets/icons/home.svg
  server/api/routes/auth.route.js
  server/api/services/user.service.js
  server/data/db/connection.js
Labels: enhancement

#36 New/password reset
  README.md
  client/src/containers/Routing/index.jsx
  client/src/images/depot-logo-1.png
  client/src/reducers/index.js
  client/src/sagas/index.js
  client/src/scenes/Forgot/actions.js
  client/src/scenes/Forgot/index.jsx
  client/src/scenes/Forgot/reducer.js
  client/src/scenes/Forgot/saga/watchers.js
  client/src/scenes/Forgot/saga/workers/forgotPassword.js
  client/src/scenes/Forgot/saga/workers/index.js
  client/src/scenes/Forgot/styles.module.scss
  client/src/scenes/Forgot/types.js
  client/src/scenes/Login/index.jsx
  client/src/scenes/Login/styles.module.scss
  client/src/scenes/Reset/actions.js
  client/src/scenes/Reset/index.jsx
  client/src/scenes/Reset/reducer.js
  client/src/scenes/Reset/saga/watchers.js
  client/src/scenes/Reset/saga/workers/index.js
  client/src/scenes/Reset/saga/workers/resetPassword.js
  client/src/scenes/Reset/styles.module.scss
  client/src/scenes/Reset/types.js
  client/src/scenes/index.js
  client/src/services/userService.js
  client/src/store.js
  server/.env.example
  server/api/routes/user.route.js
  server/api/services/user.service.js
  server/config/aws.config.js
  server/config/db.config.js
  server/data/db/connection.js
  server/data/repositories/user.repository.js
  server/helpers/email.helper.js
  server/helpers/token.helper.js
  server/package.json
  server/server.js
Labels: enhancement

#42 Fix/remove direct endpoints
  client/.env.example
  client/src/containers/Profile/sagas.js
  client/src/services/userService.js
  server/data/repositories/user.repository.js
  server/server.js
Labels: bug

#43 New/fetch git repos to dashboard page double
  client/package.json
  client/src/reducers/index.js
  client/src/sagas/index.js
  client/src/scenes/Dashboard/actions.js
  client/src/scenes/Dashboard/index.jsx
  client/src/scenes/Dashboard/reducer.js
  client/src/scenes/Dashboard/sagas.js
  client/src/scenes/Dashboard/styles.module.scss
  client/src/scenes/Dashboard/types.js
  client/src/scenes/Forgot/index.jsx
  client/src/services/repositoryService.js
  server/api/routes/repo.route.js
  server/api/services/repo.service.js
  server/package.json
Labels: enhancement

#46 fix: Fixed server routes
  client/src/containers/Routing/index.jsx
  client/src/services/authService.js
  client/src/services/branchesService.js
  client/src/services/commitsService.js
  client/src/services/repositoryService.js
  client/src/services/signupService.js
  client/src/services/userService.js
  server/api/middlewares/authorization.middleware.js
  server/api/routes/auth.route.js
  server/api/routes/commit.route.js
  server/api/routes/index.js
  server/api/routes/user.route.js
  server/config/routes-white-list.config.js
  server/server.js
Labels: bug

#49 New/repository header
  client/src/components/RepositoryHeader/index.jsx
  client/src/components/RepositoryHeader/styles.module.scss
  client/src/containers/CommitsPage/index.jsx
  client/src/containers/IssuesTab/index.jsx
  client/src/containers/Routing/index.jsx
  client/src/scenes/CodeTab/index.jsx
  client/src/scenes/Repository/index.jsx
  client/src/scenes/Repository/styles.module.scss
Labels: enhancement

#60 fix: Fixed helper typo and unused variable; prettified
  client/src/components/RepositoriesList/index.jsx
  client/src/components/RepositoryItem/index.jsx
  server/api/routes/repo.route.js
  server/data/models/user.js
  server/data/seed-data/users.seed.js
Labels: bug

#58 New/connect code page with real data
  client/src/components/RepoFileTree/index.jsx
  client/src/containers/Routing/index.jsx
  client/src/reducers/index.js
  client/src/routines/routines.js
  client/src/sagas/index.js
  client/src/scenes/CodeTab/index.jsx
  client/src/scenes/CodeTab/reducer.js
  client/src/scenes/CodeTab/sagas.js
  client/src/scenes/CodeTab/styles.module.scss
  client/src/services/branchesService.js
  server/api/routes/repo.route.js
  server/api/services/branch.service.js
Labels: enhancement

#64 New/set ssh keys
  README.md
  client/src/components/DeleteKeyButton/index.jsx
  client/src/containers/KeysPage/index.jsx
  client/src/containers/KeysPage/styles.module.scss
  client/src/containers/NewKeyPage/index.jsx
  client/src/containers/Profile/reducer.js
  client/src/scenes/CodeTab/reducer.js
  client/src/scenes/CodeTab/sagas.js
  client/src/scenes/Forgot/reducer.js
  client/src/scenes/Reset/reducer.js
  client/src/services/branchesService.js
  client/src/services/userService.js
  server/.env.example
  server/api/routes/user.route.js
  server/api/services/sshKey.service.js
  server/data/db/associations.js
  server/data/migrations/20190812194426-create-ssh-key.js
  server/data/models/index.js
  server/data/models/sshkey.js
  server/data/repositories/sshKey.repository.js
  server/helpers/fingerprint.helper.js
  server/package.json
Labels: enhancement

#65 Fix/invalid branch service routes
  client/src/services/branchesService.js
Labels: bug

#67 refactor: Verify routing with standarts
  client/src/containers/Routing/index.jsx
  client/src/scenes/Repository/index.jsx
Labels: enhancement

#66 New/add file structure navigation
  client/src/components/RepoFileTree/index.jsx
  client/src/scenes/CodeTab/index.jsx
  client/src/scenes/CodeTab/reducer.js
  client/src/scenes/CodeTab/sagas.js
  client/src/services/branchesService.js
  server/api/routes/repo.route.js
  server/api/services/branch.service.js
Labels: enhancement

#68 fix: Fixed wrong using PrivateRoute
  client/src/containers/Routing/index.jsx
Labels: bug

#69 fix: Fixed sign in/up links
  client/src/containers/Header/index.jsx
Labels: bug

#70 fix: Update hrefs
  client/src/containers/Header/index.jsx
  client/src/containers/Routing/index.jsx
Labels: bug

#71 Fix/wrong redirect after login
  client/src/scenes/Login/index.jsx
Labels: bug

#75 fix: Signup with Google
  client/src/scenes/Signup/index.jsx
  client/src/services/signupService.js
Labels: bug

#76 fix: Display corresponding headers for authorized users on all pages
  client/src/containers/Routing/index.jsx
  client/src/scenes/MainPage/index.jsx
  server/api/routes/repo.route.js
  server/api/services/branch.service.js
Labels: bug

#84 fix: Add link to new repository page
  client/src/components/RepositoriesList/index.jsx
  client/src/containers/Header/index.jsx
Labels: bug

#72 New/commit diff view
  client/package.json
  client/src/components/CommitsList/index.jsx
  client/src/components/DiffCommitView/index.jsx
  client/src/components/DiffCommitView/reducer.js
  client/src/components/DiffCommitView/sagas.js
  client/src/components/DiffCommitView/styles.module.scss
  client/src/containers/CommitsPage/index.jsx
  client/src/reducers/index.js
  client/src/routines/routines.js
  client/src/sagas/index.js
  client/src/scenes/Repository/index.jsx
  client/src/services/commitsService.js
  server/api/routes/repo.route.js
  server/api/services/branch.service.js
  server/api/services/commit.service.js
  server/api/services/email.service.js
  server/api/services/queue.service.js
  server/api/services/repo.service.js
  server/api/services/sshKey.service.js
  server/api/services/user.service.js
  server/data/db/associations.js
  server/data/db/connection.js
  server/data/migrations/20190812194426-create-ssh-key.js
  server/helpers/fingerprint.helper.js
Labels: enhancement

#86 Fix/fix home page routing
  client/src/containers/Routing/index.jsx
  client/src/scenes/Dashboard/index.jsx
Labels: bug

#90 fix: Update keys
  README.md
  client/.env.example
  server/.env.example
Labels: documentation

#92 fix: Reduce header size
  client/src/containers/Header/styles.module.scss
Labels: bug

#95 New/fill dashboard page with real data
  client/src/components/RepositoriesList/index.jsx
  client/src/containers/Overview/index.jsx
  client/src/reducers/index.js
  client/src/scenes/Dashboard/actions.js
  client/src/scenes/Dashboard/index.jsx
  client/src/scenes/Dashboard/reducer.js
  client/src/scenes/Dashboard/sagas.js
  client/src/scenes/Dashboard/types.js
  client/src/services/commitsService.js
  client/src/services/repositoryService.js
  server/api/routes/commit.route.js
  server/api/routes/repo.route.js
  server/api/services/commit.service.js
  server/api/services/repo.service.js
Labels: enhancement

#99 Fix/checking if repository empty
  client/src/containers/EmptyRepositoryTab/index.jsx
  client/src/containers/RepositoryTab/index.jsx
Labels: bug

#101 Fix/fix redirect from landing page
  client/src/scenes/MainPage/index.jsx
  client/src/styles/assets/landing-images/fifth-pic.svg
  client/src/styles/assets/landing-images/first-pic.svg
  client/src/styles/assets/landing-images/fourth-pic.svg
  client/src/styles/assets/landing-images/second-pic.svg
  client/src/styles/assets/landing-images/third-pic.svg
Labels: bug

#105 New/write authorized keys
  README.md
  client/src/containers/NewKeyPage/index.jsx
  client/src/scenes/MainPage/index.jsx
  server/.env.example
  server/api/routes/user.route.js
  server/api/services/ssh-key.service.js
  server/api/services/sshKey.service.js
  server/data/repositories/ssh-key.repository.js
Labels: enhancement

#109 fix: rename variables
  client/src/containers/RepositoryTab/index.jsx
  client/src/scenes/CreateRepository/index.jsx
  client/src/services/repositoryService.js
  server/api/routes/repo.route.js
  server/api/services/repo.service.js
Labels: bug

#118 Fix/fix getting last commit and tree
  client/src/components/RepoFileTree/index.jsx
  client/src/containers/CommitsPage/sagas.js
  client/src/scenes/CodeTab/index.jsx
  server/api/services/branch.service.js
  server/api/services/commit.service.js
  server/helpers/repo.helper.js
Labels: bug

#121 Fix/isolated octicon styles
  client/src/components/RepoReadme/styles.module.scss
  client/src/components/RepositoriesList/styles.module.scss
  client/src/components/RepositoryHeader/styles.module.scss
  client/src/containers/Overview/styles.module.scss
  client/src/scenes/CodeTab/styles.module.scss
  client/src/scenes/Dashboard/styles.module.scss
Labels: bug

#122 Fix/fix commits page
  client/src/components/CommitsList/index.jsx
  client/src/components/DiffCommitView/index.jsx
  client/src/containers/CommitsPage/index.jsx
Labels: bug

#119 Fix/repository page controls
  client/src/components/RepoFileTree/index.jsx
  client/src/scenes/CodeTab/index.jsx
  client/src/scenes/CodeTab/styles.module.scss
Labels: bug

#120 fix: Initial getting commits
  server/api/services/commit.service.js
Labels: bug

#125 fix: Fixed width of the repository tabs' content
  client/src/scenes/Repository/index.jsx
  client/src/scenes/Repository/styles.module.scss
Labels: bug

#137 fix: Fixed switching branches on commits page
  client/src/containers/CommitsPage/index.jsx
  client/src/scenes/MainPage/index.jsx
Labels: bug

#140 New/file manipulation
  client/package.json
  client/src/components/CommitFileForm/index.jsx
  client/src/components/CommitFileForm/styles.module.scss
  client/src/components/FilePathBreadcrumbSections/index.jsx
  client/src/components/FileViewer/index.jsx
  client/src/components/RepoFileTree/index.jsx
  client/src/containers/FileEditPage/index.jsx
  client/src/containers/FileEditPage/styles.module.scss
  client/src/containers/FileViewPage/index.jsx
  client/src/containers/FileViewPage/styles.module.scss
  client/src/scenes/CodeTab/index.jsx
  client/src/scenes/Repository/index.jsx
  client/src/services/branchesService.js
  client/src/services/commitsService.js
  server/api/routes/commit.route.js
  server/api/routes/repo.route.js
  server/api/services/branch.service.js
  server/api/services/commit.service.js
  server/api/services/repo.service.js
Labels: enhancement

#143 Fix/overview page layout
  client/src/containers/Overview/index.jsx
  client/src/containers/Overview/styles.module.scss
  client/src/scenes/Dashboard/styles.module.scss
Labels: bug

#146 Fix/get commit count
  client/src/containers/BranchesTab/index.jsx
  client/src/containers/BranchesTab/reducer.js
  client/src/scenes/CodeTab/index.jsx
  client/src/services/commitsService.js
  server/api/routes/repo.route.js
  server/api/services/commit.service.js
Labels: bug

#152 fix: Fixed pinned repositories layout
  client/src/containers/Overview/styles.module.scss
Labels: bug

#154 fix: Header logo position at desktop resolution
  client/src/containers/Header/index.jsx
Labels: bug

#156 New/repo page data
  client/src/components/FileViewer/index.jsx
  client/src/components/RepoReadme/index.jsx
  client/src/components/RepoReadme/styles.module.scss
  client/src/components/RepositoriesList/index.jsx
  client/src/components/RepositoryItem/index.jsx
  client/src/components/RepositoryItem/styles.module.scss
  client/src/components/StarLink/index.jsx
  client/src/components/StarLink/styles.module.scss
  client/src/containers/FileEditPage/index.jsx
  client/src/containers/NewKeyPage/index.jsx
  client/src/reducers/index.js
  client/src/scenes/CodeTab/actionTypes.js
  client/src/scenes/CodeTab/actions.js
  client/src/scenes/CodeTab/index.jsx
  client/src/scenes/CodeTab/reducer.js
  client/src/scenes/CodeTab/styles.module.scss
  client/src/scenes/Dashboard/index.jsx
  client/src/scenes/Dashboard/reducer.js
  client/src/services/repositoryService.js
  server/api/routes/repo.route.js
  server/api/services/branch.service.js
  server/api/services/repo.service.js
  server/data/migrations/20190817171723-create-star.js
  server/data/migrations/20190818220416-update-repository.js
  server/data/models/index.js
  server/data/models/repository.js
  server/data/models/star.js
  server/data/repositories/repository.repository.js
  server/data/repositories/star.repository.js
Labels: enhancement

#158 fix: Fixed switching branches on commits page
  client/src/containers/CommitsPage/index.jsx
Labels: bug

#160 fix: Fixed contibution calendar colors
  client/src/containers/Overview/index.jsx
Labels: bug

#163 Fix/rename repository with empty name
  client/src/components/InputError/styles.module.scss
  client/src/containers/SettingsTab/index.jsx
Labels: bug

#168 fix: Add fix for repositoryId issue and add new column for fork
  server/data/migrations/20190819031835-add-forked-from-repoid-column.js
Labels: bug

#167 New/ui styles and branding
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/components/Footer/index.jsx
  client/src/components/Footer/styles.module.scss
  client/src/components/InputError/styles.module.scss
  client/src/components/RepositoriesList/styles.module.scss
  client/src/containers/Header/index.jsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/KeysPage/index.jsx
  client/src/containers/NewKeyPage/index.jsx
  client/src/containers/Overview/index.jsx
  client/src/containers/Overview/styles.module.scss
  client/src/containers/SettingsProfile/index.jsx
  client/src/containers/SettingsTab/index.jsx
  client/src/containers/SettingsTab/styles.module.scss
  client/src/scenes/CodeTab/styles.module.scss
  client/src/scenes/CreateOrganization/index.jsx
  client/src/scenes/CreateRepository/index.jsx
  client/src/scenes/Forgot/index.jsx
  client/src/scenes/Login/index.jsx
  client/src/scenes/MainPage/index.jsx
  client/src/scenes/MainPage/styles.module.scss
  client/src/scenes/Reset/index.jsx
  client/src/scenes/Signup/index.jsx
  client/src/semantic-ui/site/globals/site.overrides
  client/src/semantic-ui/site/globals/site.variables
  client/src/styles/assets/icons/home.svg
  client/src/styles/assets/icons/logo_icon.svg
  client/src/styles/assets/landing-images/fifth-pic.svg
  client/src/styles/assets/landing-images/first-pic.svg
  client/src/styles/assets/landing-images/logo.svg
  server/api/services/organization.service.js
Labels: enhancement

#170 Patch/code highlighting
  client/src/components/FileViewer/index.jsx
  client/src/scenes/MainPage/styles.module.scss
Labels: enhancement

#173 New/fork functionality
  client/src/components/ForkButton/index.jsx
  client/src/components/ForkButton/sagas.js
  client/src/services/repositoryService.js
  server/api/routes/repo.route.js
  server/api/services/repo.service.js
  server/data/db/associations.js
  server/data/migrations/20190821132843-remove-repository-id-column-from-repositories.js
  server/package.json
Labels: enhancement

#172 fix: Display Pull requests in header
  client/src/containers/Header/index.jsx
  client/src/containers/Header/styles.module.scss
Labels: bug

#175 fix: Fixed arrow alignment and changed icon in dropdown to correspond…
  client/src/containers/Header/index.jsx
  client/src/containers/Header/styles.module.scss
  client/src/services/repositoryService.js
Labels: bug

#177 fix: Issues page error after reload
  client/src/components/IssueComments/index.jsx
  client/src/components/IssueComments/sagas.js
  client/src/components/IssuesList/index.jsx
  client/src/containers/CreateIssuePage/index.jsx
  client/src/containers/IssuesTab/index.jsx
  client/src/containers/RepositoryTab/sagas.js
  client/src/services/issuesService.js
Labels: bug

#174 Fix/replace data values
  server/api/services/email.service.js
  server/api/services/issue.service.js
  server/api/services/organization.service.js
  server/data/models/issue.js
  server/data/models/issueComment.js
  server/data/repositories/issue-comment.repository.js
  server/data/repositories/issue.repository.js
  server/data/repositories/user.repository.js
Labels: bug

#181 fix: Fixed displaying of the user's page after deleting repo
  client/src/containers/SettingsTab/index.jsx
Labels: bug

#182 fix: Fixed connect`s arguments
  client/src/components/FilePathBreadcrumbSections/index.jsx
  client/src/scenes/CodeTab/index.jsx
Labels: bug

#183 fix: Fixed disaplying quantity of user's items
  client/src/components/DashboardHeader/index.jsx
Labels: bug

#184 Fix/name of starred repository
  client/src/containers/StarsTab/index.js
  server/data/repositories/star.repository.js
Labels: bug

#187 fix: Fixed initializing repo with README
  server/api/services/commit.service.js
  server/api/services/repo.service.js
Labels: bug

#188 fix: display user additional info
  client/src/components/AdditionalUserInfo/index.js
  client/src/components/AdditionalUserInfo/styles.module.scss
  client/src/scenes/Dashboard/index.jsx
Labels: bug

#192 fix: Fixed redirect after commiting file edit
  client/src/containers/FileEditPage/index.jsx
Labels: bug

#194 fix: Header font
  client/src/containers/Header/styles.module.scss
Labels: bug

#201 fix: Brought the method back to get data on the brances page
  client/src/containers/BranchesTab/sagas.js
Labels: bug

#198 fix: Changed order of request declarations, so request can pass to the proper handler
  server/api/routes/user.route.js
Labels: bug

#200 New/fork functionality
  client/src/components/ForkButton/index.jsx
  client/src/components/ForkButton/reducer.js
  client/src/components/ForkButton/sagas.js
  client/src/components/RepositoryHeader/index.jsx
  client/src/components/RepositoryHeader/styles.module.scss
  client/src/containers/RepositoryTab/reducer.js
  client/src/scenes/Repository/index.jsx
  server/api/routes/organization.route.js
  server/api/routes/repo.route.js
  server/api/services/repo.service.js
  server/data/db/associations.js
  server/data/models/commit.js
  server/data/models/commitcomment.js
  server/data/repositories/repository.repository.js
Labels: enhancement

#205 fix: update user stats after starring repo
  client/src/containers/RepositoriesList/index.jsx
  client/src/containers/StarsTab/index.js
  client/src/scenes/Dashboard/index.jsx
Labels: bug

#213 Fix/issues numbers
  client/src/components/IssuesList/index.jsx
  client/src/containers/CreateIssuePage/index.jsx
  client/src/containers/IssuesTab/index.jsx
  server/api/routes/repo.route.js
  server/data/migrations/20190823130659-add-issue-number-column.js
  server/data/migrations/20190823215738-add-issue-number-constraint.js
  server/data/models/issue.js
  server/data/repositories/issue.repository.js
Labels: bug

#216 New/fork functionality
  client/src/components/ForkButton/actionTypes.js
  client/src/components/ForkButton/actions.js
  client/src/components/ForkButton/index.jsx
  client/src/components/ForkButton/reducer.js
  client/src/components/ForkButton/sagas.js
  client/src/components/RepositoryHeader/index.jsx
  client/src/reducers/index.js
  client/src/routines/routines.js
  client/src/sagas/index.js
  server/api/services/repo.service.js
  server/data/migrations/20190823091110-create-tables.js
  server/data/migrations/20190823100528-add-constraints.js
  server/package.json
Labels: bug

#225 fix: Update contribution-activity route
  client/src/services/commitsService.js
  server/api/routes/commit.route.js
  server/api/routes/users.route.js
Labels: bug

#239 New/real time comments updates
  client/.env.example
  client/package.json
  client/src/components/DiffCommitView/index.jsx
  client/src/components/IssueComments/index.jsx
  server/package.json
  server/server.js
  server/socket/handlers.js
Labels: enhancement

#241 New/git hooks
  README.md
  client/src/containers/KeysPage/index.jsx
  client/src/containers/OrgPeopleTab/index.jsx
  client/src/scenes/OrganizationDashboard/index.jsx
  client/src/scenes/OrganizationPeople/index.jsx
  client/src/services/userService.js
  scripts/git-hooks/pre-receive
  scripts/git-hooks/update
  server/.env.example
  server/api/services/branch.service.js
  server/api/services/commit.service.js
  server/api/services/queue.service.js
  server/api/services/repo.service.js
  server/api/services/ssh-key.service.js
  server/api/services/user.service.js
  server/config/rabbitmq.config.js
  server/config/ssh-key.config.js
  server/data/db/associations.js
  server/data/migrations/20190823130659-add-issue-number-column.js
  server/data/migrations/20190823215738-add-issue-number-constraint.js
  server/data/migrations/20190825203655-create-branch.js
  server/data/migrations/20190826114328-add-default-branch.js
  server/data/migrations/20190826130258-add-message-userid.js
  server/data/migrations/20190826133557-add-branch-constraint.js
  server/data/models/branch.js
  server/data/models/commit.js
  server/data/models/index.js
  server/data/repositories/branch.repository.js
  server/data/repositories/commit.repository.js
  server/data/repositories/issue.repository.js
  server/helpers/repo.helper.js
Labels: enhancement

#246 Patch/update setting menu styles
  client/src/scenes/Settings/index.jsx
  client/src/styles/common.scss
Labels: enhancement

#247 fix: Fixed README styles so content doesn't overflow
  client/src/components/RepoReadme/index.jsx
  client/src/components/RepoReadme/styles.module.scss
Labels: bug

#249 Fix/menu item background
  client/src/styles/common.scss
Labels: bug

#251 New/view raw file
  README.md
  client/.env.example
  client/src/app.config.js
  client/src/containers/FileViewPage/index.jsx
  client/src/containers/FileViewPage/styles.module.scss
  client/src/services/userService.js
  raw-server/.env.example
  raw-server/.eslintrc
  raw-server/package.json
  raw-server/server.js
  server/api/routes/files.route.js
  server/api/routes/index.js
  server/api/routes/repo.route.js
  server/api/services/branch.service.js
  server/api/services/files.service.js
  server/api/services/repo.service.js
  server/config/routes-white-list.config.js
Labels: enhancement

#262 New/language stats
  client/src/containers/LanguageStats/index.jsx
  client/src/containers/LanguageStats/styles.module.scss
  client/src/scenes/CodeTab/index.jsx
  client/src/scenes/CodeTab/styles.module.scss
  client/src/services/statsService.js
  scripts/git-hooks/update
  server/api/routes/repo.route.js
  server/api/services/language-stats.service.js
  server/api/services/language.service.js
  server/data/db/associations.js
  server/data/migrations/20190829135956-create-language.js
  server/data/migrations/20190829150355-create-language-stats.js
  server/data/migrations/20190830080922-add-language-stats-constraint.js
  server/data/models/index.js
  server/data/models/language.js
  server/data/models/languageStats.js
  server/data/repositories/language-stats.repository.js
  server/data/repositories/language.repository.js
  server/data/seeders/20190829141154-languages.js
  server/helpers/repo.helper.js
  server/package.json
Labels: enhancement

#263 fix: Added verification for filename uniqueness
  client/src/containers/FileEditPage/index.jsx
  client/src/containers/FileEditPage/styles.module.scss
  client/src/services/branchesService.js
  server/api/routes/repo.route.js
  server/api/routes/users.route.js
  server/api/services/branch.service.js
  server/api/services/issue.service.js
  server/api/services/user.service.js
Labels: bug
